# Generated by Django 4.2.11 on 2024-03-17 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
